import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Babovkejsn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="flex items-center justify-center mt-10 py-2">
          <Image 
            src="/babovka_logo.png"
            alt="mini logo babovkejsn"
            width={100}
            height={80}
          />
        </div>
      </body>
    </html>
  );
}
